### ISSUE TITLE
Failing Tests: configserver-ubuntu-1204

### ISSUE THREAD

**Issue by zarry** [chef-brigade/mongodb-cookbook#57]
```
I, [2015-07-15T20:42:27.153451 #14844]  INFO -- configserver-ubuntu-1204: -----> Cleaning up any prior instances of <configserver-ubuntu-1204>
I, [2015-07-15T20:42:27.153582 #14844]  INFO -- configserver-ubuntu-1204: -----> Destroying <configserver-ubuntu-1204>...
I, [2015-07-15T20:42:27.154441 #14844]  INFO -- configserver-ubuntu-1204: Finished destroying <configserver-ubuntu-1204> (0m0.00s).
I, [2015-07-15T20:42:27.154633 #14844]  INFO -- configserver-ubuntu-1204: -----> Testing <configserver-ubuntu-1204>
I, [2015-07-15T20:42:27.154715 #14844]  INFO -- configserver-ubuntu-1204: -----> Creating <configserver-ubuntu-1204>...
I, [2015-07-15T20:42:29.224955 #14844]  INFO -- configserver-ubuntu-1204: Bringing machine 'default' up with 'virtualbox' provider...
I, [2015-07-15T20:42:29.449195 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Importing base box 'opscode-ubuntu-12.04'...
I, [2015-07-15T20:42:38.553716 #14844]  INFO -- configserver-ubuntu-1204: 
[KProgress: 10%
[KProgress: 20%
[KProgress: 40%
[KProgress: 60%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
I, [2015-07-15T20:42:39.286182 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Setting the name of the VM: kitchen-mongodb-cookbook-configserver-ubuntu-1204_default_1437007359235_39096
I, [2015-07-15T20:42:41.211949 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Fixed port collision for 22 => 2222. Now on port 2211.
I, [2015-07-15T20:42:41.265356 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Clearing any previously set network interfaces...
I, [2015-07-15T20:42:41.325072 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Preparing network interfaces based on configuration...
I, [2015-07-15T20:42:41.325791 #14844]  INFO -- configserver-ubuntu-1204:     default: Adapter 1: nat
I, [2015-07-15T20:42:41.374892 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Forwarding ports...
I, [2015-07-15T20:42:41.459405 #14844]  INFO -- configserver-ubuntu-1204:     default: 22 => 2211 (adapter 1)
I, [2015-07-15T20:42:41.639172 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Running 'pre-boot' VM customizations...
I, [2015-07-15T20:42:41.704481 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Booting VM...
I, [2015-07-15T20:42:42.311081 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Waiting for machine to boot. This may take a few minutes...    default: SSH address: 127.0.0.1:2211
I, [2015-07-15T20:42:42.311260 #14844]  INFO -- configserver-ubuntu-1204:     default: SSH username: vagrant
I, [2015-07-15T20:42:42.311514 #14844]  INFO -- configserver-ubuntu-1204:     default: SSH auth method: private key
I, [2015-07-15T20:42:57.464796 #14844]  INFO -- configserver-ubuntu-1204:     default: Warning: Connection timeout. Retrying...
I, [2015-07-15T20:42:57.837703 #14844]  INFO -- configserver-ubuntu-1204:     default: 
I, [2015-07-15T20:42:57.837764 #14844]  INFO -- configserver-ubuntu-1204:     default: Vagrant insecure key detected. Vagrant will automatically replace
I, [2015-07-15T20:42:57.837789 #14844]  INFO -- configserver-ubuntu-1204:     default: this with a newly generated keypair for better security.
I, [2015-07-15T20:42:58.265596 #14844]  INFO -- configserver-ubuntu-1204:     default: 
I, [2015-07-15T20:42:58.265708 #14844]  INFO -- configserver-ubuntu-1204:     default: Inserting generated public key within guest...
I, [2015-07-15T20:42:58.335787 #14844]  INFO -- configserver-ubuntu-1204:     default: Removing insecure key from the guest if it's present...
I, [2015-07-15T20:42:58.426239 #14844]  INFO -- configserver-ubuntu-1204:     default: Key inserted! Disconnecting and reconnecting using new SSH key...
I, [2015-07-15T20:42:59.037054 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Machine booted and ready!
I, [2015-07-15T20:42:59.037351 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Checking for guest additions in VM...
I, [2015-07-15T20:42:59.079066 #14844]  INFO -- configserver-ubuntu-1204: ==> default: Setting hostname...
I, [2015-07-15T20:42:59.267111 #14844]  INFO -- configserver-ubuntu-1204: The following SSH command responded with a non-zero exit status.
I, [2015-07-15T20:42:59.267172 #14844]  INFO -- configserver-ubuntu-1204: Vagrant assumes that this means the command failed!
I, [2015-07-15T20:42:59.267194 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267211 #14844]  INFO -- configserver-ubuntu-1204: hostnamectl set-hostname 'configserver-ubuntu-1204'
I, [2015-07-15T20:42:59.267226 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267239 #14844]  INFO -- configserver-ubuntu-1204: Stdout from the command:
I, [2015-07-15T20:42:59.267252 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267266 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267280 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267295 #14844]  INFO -- configserver-ubuntu-1204: Stderr from the command:
I, [2015-07-15T20:42:59.267308 #14844]  INFO -- configserver-ubuntu-1204: 
I, [2015-07-15T20:42:59.267323 #14844]  INFO -- configserver-ubuntu-1204: stdin: is not a tty
I, [2015-07-15T20:42:59.267339 #14844]  INFO -- configserver-ubuntu-1204: bash: line 2: hostnamectl: command not found
E, [2015-07-15T20:42:59.320792 #14844] ERROR -- configserver-ubuntu-1204: Create failed on instance <configserver-ubuntu-1204>.
E, [2015-07-15T20:42:59.321021 #14844] ERROR -- configserver-ubuntu-1204: ------Exception-------
E, [2015-07-15T20:42:59.321059 #14844] ERROR -- configserver-ubuntu-1204: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2015-07-15T20:42:59.321086 #14844] ERROR -- configserver-ubuntu-1204: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'opscode-ubuntu-12.04'...

[KProgress: 10%
[KProgress: 20%
[KProgress: 40%
[KProgress: 60%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-mongodb-cookbook-configserver-ubuntu-1204_default_1437007359235_39096
==> default: Fixed port collision for 22 => 2222. Now on port 2211.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2211 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2211
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
STDERR: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostnamectl set-hostname 'configserver-ubuntu-1204'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: hostnamectl: command not found
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2015-07-15T20:42:59.321229 #14844] ERROR -- configserver-ubuntu-1204: ---Nested Exception---
E, [2015-07-15T20:42:59.321249 #14844] ERROR -- configserver-ubuntu-1204: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2015-07-15T20:42:59.321267 #14844] ERROR -- configserver-ubuntu-1204: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'opscode-ubuntu-12.04'...

[KProgress: 10%
[KProgress: 20%
[KProgress: 40%
[KProgress: 60%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-mongodb-cookbook-configserver-ubuntu-1204_default_1437007359235_39096
==> default: Fixed port collision for 22 => 2222. Now on port 2211.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2211 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2211
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
STDERR: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostnamectl set-hostname 'configserver-ubuntu-1204'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: hostnamectl: command not found
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2015-07-15T20:42:59.321346 #14844] ERROR -- configserver-ubuntu-1204: ------Backtrace-------
E, [2015-07-15T20:42:59.321366 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:73:in `rescue in run_command'
E, [2015-07-15T20:42:59.321380 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:61:in `run_command'
E, [2015-07-15T20:42:59.321394 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:318:in `run_command'
E, [2015-07-15T20:42:59.321410 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:302:in `run'
E, [2015-07-15T20:42:59.321426 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:348:in `run_vagrant_up'
E, [2015-07-15T20:42:59.321439 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:88:in `create'
E, [2015-07-15T20:42:59.321452 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-07-15T20:42:59.321467 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-07-15T20:42:59.321481 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:485:in `call'
E, [2015-07-15T20:42:59.321496 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:485:in `block in synchronize_or_call'
E, [2015-07-15T20:42:59.321511 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:483:in `synchronize'
E, [2015-07-15T20:42:59.321532 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:483:in `synchronize_or_call'
E, [2015-07-15T20:42:59.321547 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-07-15T20:42:59.321560 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-07-15T20:42:59.321574 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
E, [2015-07-15T20:42:59.321658 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-07-15T20:42:59.321672 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-07-15T20:42:59.321685 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-07-15T20:42:59.321697 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
E, [2015-07-15T20:42:59.321710 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-07-15T20:42:59.321722 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:160:in `verify'
E, [2015-07-15T20:42:59.321735 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-07-15T20:42:59.321747 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-07-15T20:42:59.321759 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:185:in `test'
E, [2015-07-15T20:42:59.321772 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
E, [2015-07-15T20:42:59.321784 #14844] ERROR -- configserver-ubuntu-1204: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-07-15T20:42:59.321797 #14844] ERROR -- configserver-ubuntu-1204: ----------------------
```

**Comment by zarry** [comment]
Fixed with upgraded vagrant
